import { Code2, ExternalLink, Puzzle, Swords } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { abilities, codeforcesChallenge, mathChallenge } from "@/lib/game-mock";
import { AbilityCard } from "./ability-card";
import { EnergyBar } from "./energy-bar";
import { GoldPanel, StatusIndicator } from "./game-shell";

export function CommanderPanel({ energy, onEnergy, onNotify }: { energy: number; onEnergy: (value: number) => void; onNotify: (message: string) => void }) {
  const [tab,setTab] = useState<"challenges"|"abilities">("challenges"); const [answer,setAnswer] = useState(""); const [mathState,setMathState] = useState<"idle"|"wrong"|"solved">("idle"); const [selectedAbility,setSelectedAbility] = useState("Scout"); const [verifyState,setVerifyState] = useState<"idle"|"checking"|"missing">("idle");
  const verifyMath = () => { if (answer.trim() === mathChallenge.answer) { setMathState("solved"); onEnergy(Math.min(100,energy + 30)); onNotify("Math challenge verified — energy restored."); } else setMathState("wrong"); };
  const verifyCodeforces = () => { setVerifyState("checking"); window.setTimeout(() => { setVerifyState("missing"); onNotify("No accepted submission found yet."); },700); };
  return <GoldPanel className="flex h-full min-h-0 w-full flex-col p-4"><header className="flex items-start justify-between"><div><h2 className="font-brand text-xl font-bold tracking-[0.08em] text-gold">COMMANDER</h2><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Tactical Uplink</p></div><StatusIndicator label="ONLINE"/></header><div className="mt-3"><EnergyBar energy={energy}/></div><div className="mt-3 grid grid-cols-2 gap-2" role="tablist"><Button variant="hudTab" aria-selected={tab === "challenges"} role="tab" onClick={() => setTab("challenges")}><Puzzle/>CHALLENGES</Button><Button variant="hudTab" aria-selected={tab === "abilities"} role="tab" onClick={() => setTab("abilities")}><Swords/>ABILITIES</Button></div>
    <div className="mt-3 min-h-0 flex-1 overflow-y-auto pr-1">{tab === "challenges" ? <div className="space-y-3"><section className="rounded-md border border-primary/45 bg-background/50 p-4"><h3 className="flex items-center gap-2 text-xs font-bold"><Puzzle className="size-4 text-player-8"/>MATH CHALLENGE</h3><p className="mt-4 text-base font-medium">{mathChallenge.question}</p><Input value={answer} onChange={(e) => { setAnswer(e.target.value); setMathState("idle"); }} onKeyDown={(e) => { if(e.key === "Enter" && answer.trim()) verifyMath(); }} placeholder="Enter your answer..." className="mt-3 h-11 bg-background/65"/><Button variant="game" className="mt-3 w-full" onClick={verifyMath} disabled={!answer.trim() || mathState === "solved"}>{mathState === "solved" ? "Answer Verified" : "Verify Answer"}</Button>{mathState === "wrong" && <p className="mt-2 text-xs text-danger">Incorrect answer. Try again.</p>}{mathState === "solved" && <p className="mt-2 text-xs text-success">Correct. Commander energy increased.</p>}</section><div className="flex items-center gap-3 text-[10px] font-bold text-muted-foreground"><i className="h-px flex-1 bg-gold/40"/>OR<i className="h-px flex-1 bg-gold/40"/></div><section className="rounded-md border border-primary/60 bg-background/50 p-4"><h3 className="flex items-center gap-2 text-xs font-bold"><Code2 className="size-4 text-primary"/>CODEFORCES CHALLENGE</h3><div className="mt-3 flex items-center justify-between gap-3"><div><p className="text-xs text-muted-foreground">{codeforcesChallenge.id}</p><p className="font-semibold">{codeforcesChallenge.name}</p></div><Button asChild variant="ghost" size="sm" className="text-primary"><a href={codeforcesChallenge.url} target="_blank" rel="noreferrer">Open in Codeforces<ExternalLink/></a></Button></div><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Solve on Codeforces using your handle.<br/>Get Accepted, then verify.</p><Button variant="game" className="mt-4 w-full" onClick={verifyCodeforces} disabled={verifyState === "checking"}>{verifyState === "checking" ? "Checking…" : "Verify Solution"}</Button>{verifyState === "missing" && <p className="mt-2 text-xs text-gold">No accepted submission found yet.</p>}</section></div> : <div className="grid grid-cols-2 gap-2">{abilities.map((ability) => <AbilityCard key={ability.name} ability={ability} energy={energy} selected={selectedAbility === ability.name} onSelect={() => setSelectedAbility(ability.name)} onUse={() => { onEnergy(Math.max(0,energy - ability.cost)); onNotify(`${ability.name} deployed for demonstration.`); }}/>)}</div>}</div>
  </GoldPanel>;
}